/**
 * Build-time script: reads data/schemas/*.json and data/sample-credit-cards/*.json,
 * generates TypeScript types from each schema, validates samples against their schema,
 * and writes src/generated-data.ts with exported types and sampleCreditCards array.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import Ajv from "ajv";
import { compile } from "json-schema-to-typescript";

const ROOT = resolve(import.meta.dirname, "../../..");
const DATA_DIR = join(ROOT, "data");
const SCHEMAS_DIR = join(DATA_DIR, "schemas");
const SAMPLE_CARDS_DIR = join(DATA_DIR, "sample-credit-cards");
const OUT_FILE = join(ROOT, "packages/mcp-server/src/generated-data.ts");

/** Schema filename (e.g. "credit-card.schema.json") → type name ("CreditCard"). */
function schemaFilenameToTypeName(filename: string): string {
  const base = filename.replace(/\.schema\.json$/i, "");
  return base
    .split(/[-_]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join("");
}

/** List JSON files in a directory (non-recursive). */
async function listJsonFiles(dir: string): Promise<string[]> {
  const names = await readdir(dir);
  return names.filter((n) => n.endsWith(".json")).sort();
}

async function main() {
  const schemaFiles = await listJsonFiles(SCHEMAS_DIR);
  const sampleFiles = await listJsonFiles(SAMPLE_CARDS_DIR);

  if (schemaFiles.length === 0) {
    throw new Error(`No schema files in ${SCHEMAS_DIR}`);
  }

  // Load schemas and generate types
  const schemaEntries: { typeName: string; schema: object; ts: string }[] = [];
  for (const filename of schemaFiles) {
    const path = join(SCHEMAS_DIR, filename);
    const content = await readFile(path, "utf-8");
    const schema = JSON.parse(content) as Record<string, unknown>;
    const typeName = schemaFilenameToTypeName(filename);
    const schemaWithTitle = { ...schema, title: typeName };
    const ts = await compile(schemaWithTitle, typeName, {
      bannerComment: "",
      unreachableDefinitions: true,
    });
    schemaEntries.push({ typeName, schema, ts });
  }

  // We use the first schema for sample-credit-cards (only one schema today).
  // If you add more schemas/sample dirs, map sample dir → schema here.
  const creditCardSchemaEntry = schemaEntries.find(
    (e) => e.typeName === "CreditCard"
  );
  if (!creditCardSchemaEntry) {
    throw new Error(
      "Expected a schema that compiles to type CreditCard (e.g. credit-card.schema.json)"
    );
  }

  const ajv = new Ajv({ strict: false, validateSchema: false });
  const validate = ajv.compile(creditCardSchemaEntry.schema as object);

  // Load and validate each sample file
  const sampleEntries: {
    relativePath: string;
    content: string;
    data: unknown;
  }[] = [];
  for (const filename of sampleFiles) {
    const absPath = join(SAMPLE_CARDS_DIR, filename);
    const content = await readFile(absPath, "utf-8");
    let data: unknown;
    try {
      data = JSON.parse(content);
    } catch (e) {
      console.error(`Invalid JSON: ${absPath}`);
      throw e;
    }
    const ok = validate(data);
    if (!ok) {
      console.error(`Schema validation failed: ${absPath}`);
      console.error(JSON.stringify(validate.errors, null, 2));
      process.exit(1);
    }
    sampleEntries.push({
      relativePath: `sample-credit-cards/${filename}`,
      content,
      data,
    });
  }

  // Emit generated-data.ts
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/embed-data.ts — do not edit",
    "// Re-generate with: bun run embed-data",
    "",
  ];

  for (const { ts } of schemaEntries) {
    lines.push(ts.trimEnd());
    lines.push("");
  }

  const creditCardTypeName = creditCardSchemaEntry.typeName;

  // Export schema object for get_schema
  lines.push(
    `export const creditCardSchema = ${JSON.stringify(creditCardSchemaEntry.schema)} as const;`
  );
  lines.push("");

  lines.push(
    `export const sampleCreditCardPaths: string[] = ${JSON.stringify(sampleEntries.map((e) => e.relativePath))};`
  );
  lines.push("");

  lines.push(
    `export const sampleCreditCards: ${creditCardTypeName}[] = [`
  );
  for (const { content } of sampleEntries) {
    const escaped = JSON.stringify(content);
    lines.push(`  JSON.parse(${escaped}) as ${creditCardTypeName},`);
  }
  lines.push("];");
  lines.push("");

  await writeFile(OUT_FILE, lines.join("\n"), "utf-8");
  console.log(
    `Generated ${OUT_FILE}: ${schemaEntries.length} type(s), ${sampleEntries.length} sample card(s)`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
