/**
 * Build-time script: walks the repo's data/ directory and generates
 * src/generated-data.ts with all JSON files embedded as string constants.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../../..");
const DATA_DIR = join(ROOT, "data");
const OUT_FILE = join(ROOT, "packages/mcp-server/src/generated-data.ts");

interface FileEntry {
  relativePath: string;
  content: string;
}

async function walkJson(dir: string): Promise<FileEntry[]> {
  const entries: FileEntry[] = [];
  const items = await readdir(dir, { withFileTypes: true });
  for (const item of items) {
    const fullPath = join(dir, item.name);
    if (item.isDirectory()) {
      entries.push(...(await walkJson(fullPath)));
    } else if (item.name.endsWith(".json")) {
      const content = await readFile(fullPath, "utf-8");
      entries.push({
        relativePath: relative(DATA_DIR, fullPath),
        content,
      });
    }
  }
  return entries;
}

async function main() {
  const files = await walkJson(DATA_DIR);

  const lines = [
    "// AUTO-GENERATED by scripts/embed-data.ts — do not edit",
    "// Re-generate with: bun run embed-data",
    "",
    "export interface EmbeddedFile {",
    "  path: string;",
    "  content: string;",
    "}",
    "",
    "export const embeddedFiles: EmbeddedFile[] = [",
  ];

  for (const file of files) {
    lines.push(`  {`);
    lines.push(`    path: ${JSON.stringify(file.relativePath)},`);
    lines.push(`    content: ${JSON.stringify(file.content)},`);
    lines.push(`  },`);
  }

  lines.push("];");
  lines.push("");

  await writeFile(OUT_FILE, lines.join("\n"), "utf-8");
  console.log(`Embedded ${files.length} files into ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
